// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.0
// source: proto/meets.proto

package meets

import (
	common "github.com/salahfarzin/meet/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Meet message
type Meet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OrganizerId   string                 `protobuf:"bytes,2,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Participants  []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Start         string                 `protobuf:"bytes,7,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,8,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meet) Reset() {
	*x = Meet{}
	mi := &file_proto_meets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meet) ProtoMessage() {}

func (x *Meet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meet.ProtoReflect.Descriptor instead.
func (*Meet) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{0}
}

func (x *Meet) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Meet) GetOrganizerId() string {
	if x != nil {
		return x.OrganizerId
	}
	return ""
}

func (x *Meet) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Meet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Meet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meet) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Meet) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Meet) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

// Request & Response
type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_proto_meets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{1}
}

func (x *GetOneRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meet          *Meet                  `protobuf:"bytes,1,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneResponse) Reset() {
	*x = GetOneResponse{}
	mi := &file_proto_meets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneResponse) ProtoMessage() {}

func (x *GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneResponse.ProtoReflect.Descriptor instead.
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{2}
}

func (x *GetOneResponse) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

// Request & Response
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_meets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_meets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{4}
}

// Request & Response
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   string                 `protobuf:"bytes,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_meets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllRequest) GetOrganizerId() string {
	if x != nil {
		return x.OrganizerId
	}
	return ""
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meets         []*Meet                `protobuf:"bytes,1,rep,name=meets,proto3" json:"meets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_proto_meets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllResponse) GetMeets() []*Meet {
	if x != nil {
		return x.Meets
	}
	return nil
}

// Request & Response
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meet          *Meet                  `protobuf:"bytes,1,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_meets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRequest) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Meet          *Meet                  `protobuf:"bytes,2,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_meets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResponse) GetStatus() *common.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateResponse) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

// Request & Response
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Meet          *Meet                  `protobuf:"bytes,2,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_meets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meet          *Meet                  `protobuf:"bytes,1,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_meets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_meets_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateResponse) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

var File_proto_meets_proto protoreflect.FileDescriptor

const file_proto_meets_proto_rawDesc = "" +
	"\n" +
	"\x11proto/meets.proto\x12\x05meets\x1a\x1cgoogle/api/annotations.proto\x1a\x12proto/common.proto\"\xd7\x01\n" +
	"\x04Meet\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\forganizer_id\x18\x02 \x01(\tR\vorganizerId\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x14\n" +
	"\x05start\x18\a \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\b \x01(\tR\x03end\"#\n" +
	"\rGetOneRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"1\n" +
	"\x0eGetOneResponse\x12\x1f\n" +
	"\x04meet\x18\x01 \x01(\v2\v.meets.MeetR\x04meet\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse\"2\n" +
	"\rGetAllRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\tR\vorganizerId\"3\n" +
	"\x0eGetAllResponse\x12!\n" +
	"\x05meets\x18\x01 \x03(\v2\v.meets.MeetR\x05meets\"0\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\x04meet\x18\x01 \x01(\v2\v.meets.MeetR\x04meet\"a\n" +
	"\x0eCreateResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12\x1f\n" +
	"\x04meet\x18\x02 \x01(\v2\v.meets.MeetR\x04meet\"D\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\x04meet\x18\x02 \x01(\v2\v.meets.MeetR\x04meet\"1\n" +
	"\x0eUpdateResponse\x12\x1f\n" +
	"\x04meet\x18\x01 \x01(\v2\v.meets.MeetR\x04meet2\x91\x03\n" +
	"\vMeetService\x12E\n" +
	"\x06GetAll\x12\x14.meets.GetAllRequest\x1a\x15.meets.GetAllResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/meets\x12L\n" +
	"\x06GetOne\x12\x14.meets.GetOneRequest\x1a\x15.meets.GetOneResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/meets/{uuid}\x12K\n" +
	"\x06Create\x12\x14.meets.CreateRequest\x1a\x15.meets.CreateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x04meet\"\x06/meets\x12R\n" +
	"\x06Update\x12\x14.meets.UpdateRequest\x1a\x15.meets.UpdateResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x04meet\x1a\r/meets/{uuid}\x12L\n" +
	"\x06Delete\x12\x14.meets.DeleteRequest\x1a\x15.meets.DeleteResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/meets/{uuid}B\x13Z\x11proto/meets;meetsb\x06proto3"

var (
	file_proto_meets_proto_rawDescOnce sync.Once
	file_proto_meets_proto_rawDescData []byte
)

func file_proto_meets_proto_rawDescGZIP() []byte {
	file_proto_meets_proto_rawDescOnce.Do(func() {
		file_proto_meets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_meets_proto_rawDesc), len(file_proto_meets_proto_rawDesc)))
	})
	return file_proto_meets_proto_rawDescData
}

var file_proto_meets_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_meets_proto_goTypes = []any{
	(*Meet)(nil),                  // 0: meets.Meet
	(*GetOneRequest)(nil),         // 1: meets.GetOneRequest
	(*GetOneResponse)(nil),        // 2: meets.GetOneResponse
	(*DeleteRequest)(nil),         // 3: meets.DeleteRequest
	(*DeleteResponse)(nil),        // 4: meets.DeleteResponse
	(*GetAllRequest)(nil),         // 5: meets.GetAllRequest
	(*GetAllResponse)(nil),        // 6: meets.GetAllResponse
	(*CreateRequest)(nil),         // 7: meets.CreateRequest
	(*CreateResponse)(nil),        // 8: meets.CreateResponse
	(*UpdateRequest)(nil),         // 9: meets.UpdateRequest
	(*UpdateResponse)(nil),        // 10: meets.UpdateResponse
	(*common.ResponseStatus)(nil), // 11: common.ResponseStatus
}
var file_proto_meets_proto_depIdxs = []int32{
	0,  // 0: meets.GetOneResponse.meet:type_name -> meets.Meet
	0,  // 1: meets.GetAllResponse.meets:type_name -> meets.Meet
	0,  // 2: meets.CreateRequest.meet:type_name -> meets.Meet
	11, // 3: meets.CreateResponse.status:type_name -> common.ResponseStatus
	0,  // 4: meets.CreateResponse.meet:type_name -> meets.Meet
	0,  // 5: meets.UpdateRequest.meet:type_name -> meets.Meet
	0,  // 6: meets.UpdateResponse.meet:type_name -> meets.Meet
	5,  // 7: meets.MeetService.GetAll:input_type -> meets.GetAllRequest
	1,  // 8: meets.MeetService.GetOne:input_type -> meets.GetOneRequest
	7,  // 9: meets.MeetService.Create:input_type -> meets.CreateRequest
	9,  // 10: meets.MeetService.Update:input_type -> meets.UpdateRequest
	3,  // 11: meets.MeetService.Delete:input_type -> meets.DeleteRequest
	6,  // 12: meets.MeetService.GetAll:output_type -> meets.GetAllResponse
	2,  // 13: meets.MeetService.GetOne:output_type -> meets.GetOneResponse
	8,  // 14: meets.MeetService.Create:output_type -> meets.CreateResponse
	10, // 15: meets.MeetService.Update:output_type -> meets.UpdateResponse
	4,  // 16: meets.MeetService.Delete:output_type -> meets.DeleteResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_meets_proto_init() }
func file_proto_meets_proto_init() {
	if File_proto_meets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_meets_proto_rawDesc), len(file_proto_meets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_meets_proto_goTypes,
		DependencyIndexes: file_proto_meets_proto_depIdxs,
		MessageInfos:      file_proto_meets_proto_msgTypes,
	}.Build()
	File_proto_meets_proto = out.File
	file_proto_meets_proto_goTypes = nil
	file_proto_meets_proto_depIdxs = nil
}
