// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: meets/meets.proto

package meets

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/salahfarzin/meet/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeetType int32

const (
	MeetType_MEET_TYPE_UNSPECIFIED MeetType = 0
	MeetType_IMMEDIATE_PHONE_CALL  MeetType = 1
	MeetType_CHAT                  MeetType = 2
	MeetType_PHONE_CALL            MeetType = 3
	MeetType_VIDEO_CALL            MeetType = 4
)

// Enum value maps for MeetType.
var (
	MeetType_name = map[int32]string{
		0: "MEET_TYPE_UNSPECIFIED",
		1: "IMMEDIATE_PHONE_CALL",
		2: "CHAT",
		3: "PHONE_CALL",
		4: "VIDEO_CALL",
	}
	MeetType_value = map[string]int32{
		"MEET_TYPE_UNSPECIFIED": 0,
		"IMMEDIATE_PHONE_CALL":  1,
		"CHAT":                  2,
		"PHONE_CALL":            3,
		"VIDEO_CALL":            4,
	}
)

func (x MeetType) Enum() *MeetType {
	p := new(MeetType)
	*p = x
	return p
}

func (x MeetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetType) Descriptor() protoreflect.EnumDescriptor {
	return file_meets_meets_proto_enumTypes[0].Descriptor()
}

func (MeetType) Type() protoreflect.EnumType {
	return &file_meets_meets_proto_enumTypes[0]
}

func (x MeetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetType.Descriptor instead.
func (MeetType) EnumDescriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{0}
}

// Meet message
type Meet struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OrganizerUuid    string                 `protobuf:"bytes,2,opt,name=organizer_uuid,json=organizerUuid,proto3" json:"organizer_uuid,omitempty"`
	PriceUuid        *string                `protobuf:"bytes,3,opt,name=price_uuid,json=priceUuid,proto3,oneof" json:"price_uuid,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Color            string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Start            string                 `protobuf:"bytes,7,opt,name=start,proto3" json:"start,omitempty"`
	End              string                 `protobuf:"bytes,8,opt,name=end,proto3" json:"end,omitempty"`
	ParticipantUuids []string               `protobuf:"bytes,9,rep,name=participant_uuids,json=participantUuids,proto3" json:"participant_uuids,omitempty"`
	Type             MeetType               `protobuf:"varint,10,opt,name=type,proto3,enum=meets.MeetType" json:"type,omitempty"`
	BookedAt         *string                `protobuf:"bytes,11,opt,name=booked_at,json=bookedAt,proto3,oneof" json:"booked_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Meet) Reset() {
	*x = Meet{}
	mi := &file_meets_meets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meet) ProtoMessage() {}

func (x *Meet) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meet.ProtoReflect.Descriptor instead.
func (*Meet) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{0}
}

func (x *Meet) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Meet) GetOrganizerUuid() string {
	if x != nil {
		return x.OrganizerUuid
	}
	return ""
}

func (x *Meet) GetPriceUuid() string {
	if x != nil && x.PriceUuid != nil {
		return *x.PriceUuid
	}
	return ""
}

func (x *Meet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Meet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meet) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Meet) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Meet) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Meet) GetParticipantUuids() []string {
	if x != nil {
		return x.ParticipantUuids
	}
	return nil
}

func (x *Meet) GetType() MeetType {
	if x != nil {
		return x.Type
	}
	return MeetType_MEET_TYPE_UNSPECIFIED
}

func (x *Meet) GetBookedAt() string {
	if x != nil && x.BookedAt != nil {
		return *x.BookedAt
	}
	return ""
}

// Request & Response
type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_meets_meets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{1}
}

func (x *GetOneRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meet          *Meet                  `protobuf:"bytes,1,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneResponse) Reset() {
	*x = GetOneResponse{}
	mi := &file_meets_meets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneResponse) ProtoMessage() {}

func (x *GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneResponse.ProtoReflect.Descriptor instead.
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{2}
}

func (x *GetOneResponse) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

// Request & Response
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_meets_meets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_meets_meets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{4}
}

// Request & Response
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   string                 `protobuf:"bytes,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Clinic        string                 `protobuf:"bytes,4,opt,name=clinic,proto3" json:"clinic,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	NationalId    string                 `protobuf:"bytes,7,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_meets_meets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllRequest) GetOrganizerId() string {
	if x != nil {
		return x.OrganizerId
	}
	return ""
}

func (x *GetAllRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetAllRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetAllRequest) GetClinic() string {
	if x != nil {
		return x.Clinic
	}
	return ""
}

func (x *GetAllRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetAllRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetAllRequest) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *GetAllRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetAllRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meets         []*Meet                `protobuf:"bytes,1,rep,name=meets,proto3" json:"meets,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_meets_meets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllResponse) GetMeets() []*Meet {
	if x != nil {
		return x.Meets
	}
	return nil
}

func (x *GetAllResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request & Response
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meet          *Meet                  `protobuf:"bytes,1,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_meets_meets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRequest) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Meet          *Meet                  `protobuf:"bytes,2,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_meets_meets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResponse) GetStatus() *common.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateResponse) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

// Request & Response
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Meet          *Meet                  `protobuf:"bytes,2,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_meets_meets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meet          *Meet                  `protobuf:"bytes,1,opt,name=meet,proto3" json:"meet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_meets_meets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateResponse) GetMeet() *Meet {
	if x != nil {
		return x.Meet
	}
	return nil
}

// Request & Response for availability
type GetAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"` // ISO8601 date string
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`     // ISO8601 date string
	PriceUuid     *string                `protobuf:"bytes,4,opt,name=price_uuid,json=priceUuid,proto3,oneof" json:"price_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityRequest) Reset() {
	*x = GetAvailabilityRequest{}
	mi := &file_meets_meets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRequest) ProtoMessage() {}

func (x *GetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{11}
}

func (x *GetAvailabilityRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailabilityRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetAvailabilityRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetAvailabilityRequest) GetPriceUuid() string {
	if x != nil && x.PriceUuid != nil {
		return *x.PriceUuid
	}
	return ""
}

type DateSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Times         []*TimeSlot            `protobuf:"bytes,4,rep,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateSlot) Reset() {
	*x = DateSlot{}
	mi := &file_meets_meets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateSlot) ProtoMessage() {}

func (x *DateSlot) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateSlot.ProtoReflect.Descriptor instead.
func (*DateSlot) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{12}
}

func (x *DateSlot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DateSlot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DateSlot) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DateSlot) GetTimes() []*TimeSlot {
	if x != nil {
		return x.Times
	}
	return nil
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Start         string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	BookedAt      *string                `protobuf:"bytes,5,opt,name=booked_at,json=bookedAt,proto3,oneof" json:"booked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_meets_meets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{13}
}

func (x *TimeSlot) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TimeSlot) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TimeSlot) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *TimeSlot) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TimeSlot) GetBookedAt() string {
	if x != nil && x.BookedAt != nil {
		return *x.BookedAt
	}
	return ""
}

type GetAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dates         []*DateSlot            `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityResponse) Reset() {
	*x = GetAvailabilityResponse{}
	mi := &file_meets_meets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityResponse) ProtoMessage() {}

func (x *GetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{14}
}

func (x *GetAvailabilityResponse) GetDates() []*DateSlot {
	if x != nil {
		return x.Dates
	}
	return nil
}

// Request & Response for meet types
type GetMeetTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetTypesRequest) Reset() {
	*x = GetMeetTypesRequest{}
	mi := &file_meets_meets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetTypesRequest) ProtoMessage() {}

func (x *GetMeetTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetTypesRequest.ProtoReflect.Descriptor instead.
func (*GetMeetTypesRequest) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{15}
}

func (x *GetMeetTypesRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetMeetTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []MeetType             `protobuf:"varint,1,rep,packed,name=types,proto3,enum=meets.MeetType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetTypesResponse) Reset() {
	*x = GetMeetTypesResponse{}
	mi := &file_meets_meets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetTypesResponse) ProtoMessage() {}

func (x *GetMeetTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meets_meets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetTypesResponse.ProtoReflect.Descriptor instead.
func (*GetMeetTypesResponse) Descriptor() ([]byte, []int) {
	return file_meets_meets_proto_rawDescGZIP(), []int{16}
}

func (x *GetMeetTypesResponse) GetTypes() []MeetType {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_meets_meets_proto protoreflect.FileDescriptor

const file_meets_meets_proto_rawDesc = "" +
	"\n" +
	"\x11meets/meets.proto\x12\x05meets\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xec\x02\n" +
	"\x04Meet\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12%\n" +
	"\x0eorganizer_uuid\x18\x02 \x01(\tR\rorganizerUuid\x12\"\n" +
	"\n" +
	"price_uuid\x18\x03 \x01(\tH\x00R\tpriceUuid\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x14\n" +
	"\x05start\x18\a \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\b \x01(\tR\x03end\x12+\n" +
	"\x11participant_uuids\x18\t \x03(\tR\x10participantUuids\x12#\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x0f.meets.MeetTypeR\x04type\x12 \n" +
	"\tbooked_at\x18\v \x01(\tH\x01R\bbookedAt\x88\x01\x01B\r\n" +
	"\v_price_uuidB\f\n" +
	"\n" +
	"_booked_at\"#\n" +
	"\rGetOneRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"1\n" +
	"\x0eGetOneResponse\x12\x1f\n" +
	"\x04meet\x18\x01 \x01(\v2\v.meets.MeetR\x04meet\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse\"\x94\x02\n" +
	"\rGetAllRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\tR\vorganizerId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06clinic\x18\x04 \x01(\tR\x06clinic\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12\x1f\n" +
	"\vnational_id\x18\a \x01(\tR\n" +
	"nationalId\x12\x16\n" +
	"\x06mobile\x18\b \x01(\tR\x06mobile\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\"z\n" +
	"\x0eGetAllResponse\x12!\n" +
	"\x05meets\x18\x01 \x03(\v2\v.meets.MeetR\x05meets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"0\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\x04meet\x18\x01 \x01(\v2\v.meets.MeetR\x04meet\"a\n" +
	"\x0eCreateResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12\x1f\n" +
	"\x04meet\x18\x02 \x01(\v2\v.meets.MeetR\x04meet\"D\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\x04meet\x18\x02 \x01(\v2\v.meets.MeetR\x04meet\"1\n" +
	"\x0eUpdateResponse\x12\x1f\n" +
	"\x04meet\x18\x01 \x01(\v2\v.meets.MeetR\x04meet\"\x83\x01\n" +
	"\x16GetAvailabilityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\"\n" +
	"\n" +
	"price_uuid\x18\x04 \x01(\tH\x00R\tpriceUuid\x88\x01\x01B\r\n" +
	"\v_price_uuid\"s\n" +
	"\bDateSlot\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12%\n" +
	"\x05times\x18\x04 \x03(\v2\x0f.meets.TimeSlotR\x05times\"\x92\x01\n" +
	"\bTimeSlot\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12 \n" +
	"\tbooked_at\x18\x05 \x01(\tH\x00R\bbookedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_booked_at\"@\n" +
	"\x17GetAvailabilityResponse\x12%\n" +
	"\x05dates\x18\x01 \x03(\v2\x0f.meets.DateSlotR\x05dates\")\n" +
	"\x13GetMeetTypesRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"=\n" +
	"\x14GetMeetTypesResponse\x12%\n" +
	"\x05types\x18\x01 \x03(\x0e2\x0f.meets.MeetTypeR\x05types*i\n" +
	"\bMeetType\x12\x19\n" +
	"\x15MEET_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14IMMEDIATE_PHONE_CALL\x10\x01\x12\b\n" +
	"\x04CHAT\x10\x02\x12\x0e\n" +
	"\n" +
	"PHONE_CALL\x10\x03\x12\x0e\n" +
	"\n" +
	"VIDEO_CALL\x10\x042\xed\x04\n" +
	"\vMeetService\x12E\n" +
	"\x06GetAll\x12\x14.meets.GetAllRequest\x1a\x15.meets.GetAllResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/meets\x12L\n" +
	"\x06GetOne\x12\x14.meets.GetOneRequest\x1a\x15.meets.GetOneResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/meets/{uuid}\x12K\n" +
	"\x06Create\x12\x14.meets.CreateRequest\x1a\x15.meets.CreateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x04meet\"\x06/meets\x12R\n" +
	"\x06Update\x12\x14.meets.UpdateRequest\x1a\x15.meets.UpdateResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x04meet\x1a\r/meets/{uuid}\x12L\n" +
	"\x06Delete\x12\x14.meets.DeleteRequest\x1a\x15.meets.DeleteResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/meets/{uuid}\x12t\n" +
	"\x0fGetAvailability\x12\x1d.meets.GetAvailabilityRequest\x1a\x1e.meets.GetAvailabilityResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/meets/{uuid}/availability\x12d\n" +
	"\fGetMeetTypes\x12\x1a.meets.GetMeetTypesRequest\x1a\x1b.meets.GetMeetTypesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/meets/{uuid}/typesB\x86\x02\x92A\xd3\x01\x12l\n" +
	"\tMeets API\x12*API for managing meetings and appointments\".\n" +
	"\x11Meets API Support\x1a\x19support@meets.example.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonR\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Resource not foundR\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server errorZ-github.com/salahfarzin/meet/proto/meets;meetsb\x06proto3"

var (
	file_meets_meets_proto_rawDescOnce sync.Once
	file_meets_meets_proto_rawDescData []byte
)

func file_meets_meets_proto_rawDescGZIP() []byte {
	file_meets_meets_proto_rawDescOnce.Do(func() {
		file_meets_meets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meets_meets_proto_rawDesc), len(file_meets_meets_proto_rawDesc)))
	})
	return file_meets_meets_proto_rawDescData
}

var file_meets_meets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meets_meets_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_meets_meets_proto_goTypes = []any{
	(MeetType)(0),                   // 0: meets.MeetType
	(*Meet)(nil),                    // 1: meets.Meet
	(*GetOneRequest)(nil),           // 2: meets.GetOneRequest
	(*GetOneResponse)(nil),          // 3: meets.GetOneResponse
	(*DeleteRequest)(nil),           // 4: meets.DeleteRequest
	(*DeleteResponse)(nil),          // 5: meets.DeleteResponse
	(*GetAllRequest)(nil),           // 6: meets.GetAllRequest
	(*GetAllResponse)(nil),          // 7: meets.GetAllResponse
	(*CreateRequest)(nil),           // 8: meets.CreateRequest
	(*CreateResponse)(nil),          // 9: meets.CreateResponse
	(*UpdateRequest)(nil),           // 10: meets.UpdateRequest
	(*UpdateResponse)(nil),          // 11: meets.UpdateResponse
	(*GetAvailabilityRequest)(nil),  // 12: meets.GetAvailabilityRequest
	(*DateSlot)(nil),                // 13: meets.DateSlot
	(*TimeSlot)(nil),                // 14: meets.TimeSlot
	(*GetAvailabilityResponse)(nil), // 15: meets.GetAvailabilityResponse
	(*GetMeetTypesRequest)(nil),     // 16: meets.GetMeetTypesRequest
	(*GetMeetTypesResponse)(nil),    // 17: meets.GetMeetTypesResponse
	(*common.ResponseStatus)(nil),   // 18: common.ResponseStatus
}
var file_meets_meets_proto_depIdxs = []int32{
	0,  // 0: meets.Meet.type:type_name -> meets.MeetType
	1,  // 1: meets.GetOneResponse.meet:type_name -> meets.Meet
	1,  // 2: meets.GetAllResponse.meets:type_name -> meets.Meet
	1,  // 3: meets.CreateRequest.meet:type_name -> meets.Meet
	18, // 4: meets.CreateResponse.status:type_name -> common.ResponseStatus
	1,  // 5: meets.CreateResponse.meet:type_name -> meets.Meet
	1,  // 6: meets.UpdateRequest.meet:type_name -> meets.Meet
	1,  // 7: meets.UpdateResponse.meet:type_name -> meets.Meet
	14, // 8: meets.DateSlot.times:type_name -> meets.TimeSlot
	13, // 9: meets.GetAvailabilityResponse.dates:type_name -> meets.DateSlot
	0,  // 10: meets.GetMeetTypesResponse.types:type_name -> meets.MeetType
	6,  // 11: meets.MeetService.GetAll:input_type -> meets.GetAllRequest
	2,  // 12: meets.MeetService.GetOne:input_type -> meets.GetOneRequest
	8,  // 13: meets.MeetService.Create:input_type -> meets.CreateRequest
	10, // 14: meets.MeetService.Update:input_type -> meets.UpdateRequest
	4,  // 15: meets.MeetService.Delete:input_type -> meets.DeleteRequest
	12, // 16: meets.MeetService.GetAvailability:input_type -> meets.GetAvailabilityRequest
	16, // 17: meets.MeetService.GetMeetTypes:input_type -> meets.GetMeetTypesRequest
	7,  // 18: meets.MeetService.GetAll:output_type -> meets.GetAllResponse
	3,  // 19: meets.MeetService.GetOne:output_type -> meets.GetOneResponse
	9,  // 20: meets.MeetService.Create:output_type -> meets.CreateResponse
	11, // 21: meets.MeetService.Update:output_type -> meets.UpdateResponse
	5,  // 22: meets.MeetService.Delete:output_type -> meets.DeleteResponse
	15, // 23: meets.MeetService.GetAvailability:output_type -> meets.GetAvailabilityResponse
	17, // 24: meets.MeetService.GetMeetTypes:output_type -> meets.GetMeetTypesResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_meets_meets_proto_init() }
func file_meets_meets_proto_init() {
	if File_meets_meets_proto != nil {
		return
	}
	file_meets_meets_proto_msgTypes[0].OneofWrappers = []any{}
	file_meets_meets_proto_msgTypes[11].OneofWrappers = []any{}
	file_meets_meets_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meets_meets_proto_rawDesc), len(file_meets_meets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meets_meets_proto_goTypes,
		DependencyIndexes: file_meets_meets_proto_depIdxs,
		EnumInfos:         file_meets_meets_proto_enumTypes,
		MessageInfos:      file_meets_meets_proto_msgTypes,
	}.Build()
	File_meets_meets_proto = out.File
	file_meets_meets_proto_goTypes = nil
	file_meets_meets_proto_depIdxs = nil
}
