// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: availability_templates/availability_templates.proto

package availability_templates

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/salahfarzin/meet/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvailabilityTemplate defines a recurring weekly open-hours rule for an
// organizer, e.g. "every Monday 09:00-13:00, starting 2026-08-01, until
// changed". GetAvailability lazily materializes real Meet rows from active
// templates that overlap the queried date range.
type AvailabilityTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OrganizerUuid string                 `protobuf:"bytes,2,opt,name=organizer_uuid,json=organizerUuid,proto3" json:"organizer_uuid,omitempty"`
	// weekday: 0=Sunday .. 6=Saturday.
	Weekday        int32   `protobuf:"varint,3,opt,name=weekday,proto3" json:"weekday,omitempty"`
	StartTime      string  `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "HH:MM", 24h
	EndTime        string  `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "HH:MM", 24h
	PriceUuid      *string `protobuf:"bytes,6,opt,name=price_uuid,json=priceUuid,proto3,oneof" json:"price_uuid,omitempty"`
	EffectiveFrom  string  `protobuf:"bytes,7,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`          // "YYYY-MM-DD"
	EffectiveUntil *string `protobuf:"bytes,8,opt,name=effective_until,json=effectiveUntil,proto3,oneof" json:"effective_until,omitempty"` // "YYYY-MM-DD"; unset = repeats until deactivated
	Active         bool    `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt      string  `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string  `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AvailabilityTemplate) Reset() {
	*x = AvailabilityTemplate{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityTemplate) ProtoMessage() {}

func (x *AvailabilityTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityTemplate.ProtoReflect.Descriptor instead.
func (*AvailabilityTemplate) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{0}
}

func (x *AvailabilityTemplate) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AvailabilityTemplate) GetOrganizerUuid() string {
	if x != nil {
		return x.OrganizerUuid
	}
	return ""
}

func (x *AvailabilityTemplate) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *AvailabilityTemplate) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AvailabilityTemplate) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *AvailabilityTemplate) GetPriceUuid() string {
	if x != nil && x.PriceUuid != nil {
		return *x.PriceUuid
	}
	return ""
}

func (x *AvailabilityTemplate) GetEffectiveFrom() string {
	if x != nil {
		return x.EffectiveFrom
	}
	return ""
}

func (x *AvailabilityTemplate) GetEffectiveUntil() string {
	if x != nil && x.EffectiveUntil != nil {
		return *x.EffectiveUntil
	}
	return ""
}

func (x *AvailabilityTemplate) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AvailabilityTemplate) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AvailabilityTemplate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Request & Response
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *AvailabilityTemplate  `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetTemplate() *AvailabilityTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Template      *AvailabilityTemplate  `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetStatus() *common.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateResponse) GetTemplate() *AvailabilityTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Request & Response
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Template      *AvailabilityTemplate  `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetTemplate() *AvailabilityTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *AvailabilityTemplate  `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetTemplate() *AvailabilityTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Request & Response
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{6}
}

// Request & Response
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrganizerId   string                 `protobuf:"bytes,1,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllRequest) GetOrganizerId() string {
	if x != nil {
		return x.OrganizerId
	}
	return ""
}

type GetAllResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Templates     []*AvailabilityTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_availability_templates_availability_templates_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_templates_availability_templates_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_availability_templates_availability_templates_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllResponse) GetTemplates() []*AvailabilityTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_availability_templates_availability_templates_proto protoreflect.FileDescriptor

const file_availability_templates_availability_templates_proto_rawDesc = "" +
	"\n" +
	"3availability_templates/availability_templates.proto\x12\x16availability_templates\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x97\x03\n" +
	"\x14AvailabilityTemplate\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12%\n" +
	"\x0eorganizer_uuid\x18\x02 \x01(\tR\rorganizerUuid\x12\x18\n" +
	"\aweekday\x18\x03 \x01(\x05R\aweekday\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\"\n" +
	"\n" +
	"price_uuid\x18\x06 \x01(\tH\x00R\tpriceUuid\x88\x01\x01\x12%\n" +
	"\x0eeffective_from\x18\a \x01(\tR\reffectiveFrom\x12,\n" +
	"\x0feffective_until\x18\b \x01(\tH\x01R\x0eeffectiveUntil\x88\x01\x01\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAtB\r\n" +
	"\v_price_uuidB\x12\n" +
	"\x10_effective_until\"Y\n" +
	"\rCreateRequest\x12H\n" +
	"\btemplate\x18\x01 \x01(\v2,.availability_templates.AvailabilityTemplateR\btemplate\"\x8a\x01\n" +
	"\x0eCreateResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x12H\n" +
	"\btemplate\x18\x02 \x01(\v2,.availability_templates.AvailabilityTemplateR\btemplate\"m\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12H\n" +
	"\btemplate\x18\x02 \x01(\v2,.availability_templates.AvailabilityTemplateR\btemplate\"Z\n" +
	"\x0eUpdateResponse\x12H\n" +
	"\btemplate\x18\x01 \x01(\v2,.availability_templates.AvailabilityTemplateR\btemplate\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse\"2\n" +
	"\rGetAllRequest\x12!\n" +
	"\forganizer_id\x18\x01 \x01(\tR\vorganizerId\"\\\n" +
	"\x0eGetAllResponse\x12J\n" +
	"\ttemplates\x18\x01 \x03(\v2,.availability_templates.AvailabilityTemplateR\ttemplates2\xc2\x04\n" +
	"\x1bAvailabilityTemplateService\x12~\n" +
	"\x06GetAll\x12%.availability_templates.GetAllRequest\x1a&.availability_templates.GetAllResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/meets/availability-templates\x12\x88\x01\n" +
	"\x06Create\x12%.availability_templates.CreateRequest\x1a&.availability_templates.CreateResponse\"/\x82\xd3\xe4\x93\x02):\btemplate\"\x1d/meets/availability-templates\x12\x8f\x01\n" +
	"\x06Update\x12%.availability_templates.UpdateRequest\x1a&.availability_templates.UpdateResponse\"6\x82\xd3\xe4\x93\x020:\btemplate\x1a$/meets/availability-templates/{uuid}\x12\x85\x01\n" +
	"\x06Delete\x12%.availability_templates.DeleteRequest\x1a&.availability_templates.DeleteResponse\",\x82\xd3\xe4\x93\x02&*$/meets/availability-templates/{uuid}B\xc8\x02\x92A\xf3\x01\x12\x8b\x01\n" +
	"\x1aAvailability Templates API\x128API for managing recurring weekly availability templates\".\n" +
	"\x11Meets API Support\x1a\x19support@meets.example.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonR\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Resource not foundR\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server errorZOgithub.com/salahfarzin/meet/proto/availability_templates;availability_templatesb\x06proto3"

var (
	file_availability_templates_availability_templates_proto_rawDescOnce sync.Once
	file_availability_templates_availability_templates_proto_rawDescData []byte
)

func file_availability_templates_availability_templates_proto_rawDescGZIP() []byte {
	file_availability_templates_availability_templates_proto_rawDescOnce.Do(func() {
		file_availability_templates_availability_templates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_availability_templates_availability_templates_proto_rawDesc), len(file_availability_templates_availability_templates_proto_rawDesc)))
	})
	return file_availability_templates_availability_templates_proto_rawDescData
}

var file_availability_templates_availability_templates_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_availability_templates_availability_templates_proto_goTypes = []any{
	(*AvailabilityTemplate)(nil),  // 0: availability_templates.AvailabilityTemplate
	(*CreateRequest)(nil),         // 1: availability_templates.CreateRequest
	(*CreateResponse)(nil),        // 2: availability_templates.CreateResponse
	(*UpdateRequest)(nil),         // 3: availability_templates.UpdateRequest
	(*UpdateResponse)(nil),        // 4: availability_templates.UpdateResponse
	(*DeleteRequest)(nil),         // 5: availability_templates.DeleteRequest
	(*DeleteResponse)(nil),        // 6: availability_templates.DeleteResponse
	(*GetAllRequest)(nil),         // 7: availability_templates.GetAllRequest
	(*GetAllResponse)(nil),        // 8: availability_templates.GetAllResponse
	(*common.ResponseStatus)(nil), // 9: common.ResponseStatus
}
var file_availability_templates_availability_templates_proto_depIdxs = []int32{
	0,  // 0: availability_templates.CreateRequest.template:type_name -> availability_templates.AvailabilityTemplate
	9,  // 1: availability_templates.CreateResponse.status:type_name -> common.ResponseStatus
	0,  // 2: availability_templates.CreateResponse.template:type_name -> availability_templates.AvailabilityTemplate
	0,  // 3: availability_templates.UpdateRequest.template:type_name -> availability_templates.AvailabilityTemplate
	0,  // 4: availability_templates.UpdateResponse.template:type_name -> availability_templates.AvailabilityTemplate
	0,  // 5: availability_templates.GetAllResponse.templates:type_name -> availability_templates.AvailabilityTemplate
	7,  // 6: availability_templates.AvailabilityTemplateService.GetAll:input_type -> availability_templates.GetAllRequest
	1,  // 7: availability_templates.AvailabilityTemplateService.Create:input_type -> availability_templates.CreateRequest
	3,  // 8: availability_templates.AvailabilityTemplateService.Update:input_type -> availability_templates.UpdateRequest
	5,  // 9: availability_templates.AvailabilityTemplateService.Delete:input_type -> availability_templates.DeleteRequest
	8,  // 10: availability_templates.AvailabilityTemplateService.GetAll:output_type -> availability_templates.GetAllResponse
	2,  // 11: availability_templates.AvailabilityTemplateService.Create:output_type -> availability_templates.CreateResponse
	4,  // 12: availability_templates.AvailabilityTemplateService.Update:output_type -> availability_templates.UpdateResponse
	6,  // 13: availability_templates.AvailabilityTemplateService.Delete:output_type -> availability_templates.DeleteResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_availability_templates_availability_templates_proto_init() }
func file_availability_templates_availability_templates_proto_init() {
	if File_availability_templates_availability_templates_proto != nil {
		return
	}
	file_availability_templates_availability_templates_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_availability_templates_availability_templates_proto_rawDesc), len(file_availability_templates_availability_templates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_availability_templates_availability_templates_proto_goTypes,
		DependencyIndexes: file_availability_templates_availability_templates_proto_depIdxs,
		MessageInfos:      file_availability_templates_availability_templates_proto_msgTypes,
	}.Build()
	File_availability_templates_availability_templates_proto = out.File
	file_availability_templates_availability_templates_proto_goTypes = nil
	file_availability_templates_availability_templates_proto_depIdxs = nil
}
