ALTER TABLE meets DROP COLUMN price_id;
ALTER TABLE meets
	DROP COLUMN type INT DEFAULT 0,
	DROP COLUMN old_price DOUBLE DEFAULT 0,
	DROP COLUMN discount DOUBLE DEFAULT 0,
	DROP COLUMN price DOUBLE DEFAULT 0;

