// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: specialties/specialties.proto

package specialties

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/salahfarzin/meet/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specialty is one catalogue entry. Trappists reference it by uuid from
// their profile (psychometrist users.center_details.appointments.profile).
type Specialty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// kind: "specialty" (what they treat, e.g. anxiety) or "approach" (how, e.g. CBT).
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// slug: stable, lowercase machine key, unique per kind, e.g. "anxiety".
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// names: display label per UI language code, e.g. {"en": "Anxiety", "fa": "اضطراب"}.
	Names         map[string]string `protobuf:"bytes,4,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SortOrder     int32             `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Active        bool              `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string            `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string            `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specialty) Reset() {
	*x = Specialty{}
	mi := &file_specialties_specialties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specialty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specialty) ProtoMessage() {}

func (x *Specialty) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specialty.ProtoReflect.Descriptor instead.
func (*Specialty) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{0}
}

func (x *Specialty) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Specialty) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Specialty) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Specialty) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Specialty) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Specialty) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Specialty) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Specialty) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Request & Response
type GetAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind: optional filter, "specialty" or "approach".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// include_inactive: admins managing the catalogue see deactivated entries too.
	IncludeInactive bool `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_specialties_specialties_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetAllRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialties   []*Specialty           `protobuf:"bytes,1,rep,name=specialties,proto3" json:"specialties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_specialties_specialties_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetSpecialties() []*Specialty {
	if x != nil {
		return x.Specialties
	}
	return nil
}

// Request & Response
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialty     *Specialty             `protobuf:"bytes,1,opt,name=specialty,proto3" json:"specialty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_specialties_specialties_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetSpecialty() *Specialty {
	if x != nil {
		return x.Specialty
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Specialty     *Specialty             `protobuf:"bytes,2,opt,name=specialty,proto3" json:"specialty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_specialties_specialties_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResponse) GetStatus() *common.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateResponse) GetSpecialty() *Specialty {
	if x != nil {
		return x.Specialty
	}
	return nil
}

// Request & Response
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Specialty     *Specialty             `protobuf:"bytes,2,opt,name=specialty,proto3" json:"specialty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_specialties_specialties_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetSpecialty() *Specialty {
	if x != nil {
		return x.Specialty
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialty     *Specialty             `protobuf:"bytes,1,opt,name=specialty,proto3" json:"specialty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_specialties_specialties_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetSpecialty() *Specialty {
	if x != nil {
		return x.Specialty
	}
	return nil
}

// Request & Response
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_specialties_specialties_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_specialties_specialties_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specialties_specialties_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_specialties_specialties_proto_rawDescGZIP(), []int{8}
}

var File_specialties_specialties_proto protoreflect.FileDescriptor

const file_specialties_specialties_proto_rawDesc = "" +
	"\n" +
	"\x1dspecialties/specialties.proto\x12\vspecialties\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xaf\x02\n" +
	"\tSpecialty\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x127\n" +
	"\x05names\x18\x04 \x03(\v2!.specialties.Specialty.NamesEntryR\x05names\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x1a8\n" +
	"\n" +
	"NamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\rGetAllRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\"J\n" +
	"\x0eGetAllResponse\x128\n" +
	"\vspecialties\x18\x01 \x03(\v2\x16.specialties.SpecialtyR\vspecialties\"E\n" +
	"\rCreateRequest\x124\n" +
	"\tspecialty\x18\x01 \x01(\v2\x16.specialties.SpecialtyR\tspecialty\"v\n" +
	"\x0eCreateResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.common.ResponseStatusR\x06status\x124\n" +
	"\tspecialty\x18\x02 \x01(\v2\x16.specialties.SpecialtyR\tspecialty\"Y\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x124\n" +
	"\tspecialty\x18\x02 \x01(\v2\x16.specialties.SpecialtyR\tspecialty\"F\n" +
	"\x0eUpdateResponse\x124\n" +
	"\tspecialty\x18\x01 \x01(\v2\x16.specialties.SpecialtyR\tspecialty\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse2\xb2\x03\n" +
	"\x10SpecialtyService\x12]\n" +
	"\x06GetAll\x12\x1a.specialties.GetAllRequest\x1a\x1b.specialties.GetAllResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/meets/specialties\x12h\n" +
	"\x06Create\x12\x1a.specialties.CreateRequest\x1a\x1b.specialties.CreateResponse\"%\x82\xd3\xe4\x93\x02\x1f:\tspecialty\"\x12/meets/specialties\x12o\n" +
	"\x06Update\x12\x1a.specialties.UpdateRequest\x1a\x1b.specialties.UpdateResponse\",\x82\xd3\xe4\x93\x02&:\tspecialty\x1a\x19/meets/specialties/{uuid}\x12d\n" +
	"\x06Delete\x12\x1a.specialties.DeleteRequest\x1a\x1b.specialties.DeleteResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/meets/specialties/{uuid}B\xd4\x02\x92A\x95\x02\x12\xad\x01\n" +
	"\x0fSpecialties API\x12eAdmin-managed catalogue of specialties and therapy approaches trappists pick for their public profile\".\n" +
	"\x11Meets API Support\x1a\x19support@meets.example.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonR\x1b\n" +
	"\x03404\x12\x14\n" +
	"\x12Resource not foundR\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server errorZ9github.com/salahfarzin/meet/proto/specialties;specialtiesb\x06proto3"

var (
	file_specialties_specialties_proto_rawDescOnce sync.Once
	file_specialties_specialties_proto_rawDescData []byte
)

func file_specialties_specialties_proto_rawDescGZIP() []byte {
	file_specialties_specialties_proto_rawDescOnce.Do(func() {
		file_specialties_specialties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specialties_specialties_proto_rawDesc), len(file_specialties_specialties_proto_rawDesc)))
	})
	return file_specialties_specialties_proto_rawDescData
}

var file_specialties_specialties_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_specialties_specialties_proto_goTypes = []any{
	(*Specialty)(nil),             // 0: specialties.Specialty
	(*GetAllRequest)(nil),         // 1: specialties.GetAllRequest
	(*GetAllResponse)(nil),        // 2: specialties.GetAllResponse
	(*CreateRequest)(nil),         // 3: specialties.CreateRequest
	(*CreateResponse)(nil),        // 4: specialties.CreateResponse
	(*UpdateRequest)(nil),         // 5: specialties.UpdateRequest
	(*UpdateResponse)(nil),        // 6: specialties.UpdateResponse
	(*DeleteRequest)(nil),         // 7: specialties.DeleteRequest
	(*DeleteResponse)(nil),        // 8: specialties.DeleteResponse
	nil,                           // 9: specialties.Specialty.NamesEntry
	(*common.ResponseStatus)(nil), // 10: common.ResponseStatus
}
var file_specialties_specialties_proto_depIdxs = []int32{
	9,  // 0: specialties.Specialty.names:type_name -> specialties.Specialty.NamesEntry
	0,  // 1: specialties.GetAllResponse.specialties:type_name -> specialties.Specialty
	0,  // 2: specialties.CreateRequest.specialty:type_name -> specialties.Specialty
	10, // 3: specialties.CreateResponse.status:type_name -> common.ResponseStatus
	0,  // 4: specialties.CreateResponse.specialty:type_name -> specialties.Specialty
	0,  // 5: specialties.UpdateRequest.specialty:type_name -> specialties.Specialty
	0,  // 6: specialties.UpdateResponse.specialty:type_name -> specialties.Specialty
	1,  // 7: specialties.SpecialtyService.GetAll:input_type -> specialties.GetAllRequest
	3,  // 8: specialties.SpecialtyService.Create:input_type -> specialties.CreateRequest
	5,  // 9: specialties.SpecialtyService.Update:input_type -> specialties.UpdateRequest
	7,  // 10: specialties.SpecialtyService.Delete:input_type -> specialties.DeleteRequest
	2,  // 11: specialties.SpecialtyService.GetAll:output_type -> specialties.GetAllResponse
	4,  // 12: specialties.SpecialtyService.Create:output_type -> specialties.CreateResponse
	6,  // 13: specialties.SpecialtyService.Update:output_type -> specialties.UpdateResponse
	8,  // 14: specialties.SpecialtyService.Delete:output_type -> specialties.DeleteResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_specialties_specialties_proto_init() }
func file_specialties_specialties_proto_init() {
	if File_specialties_specialties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specialties_specialties_proto_rawDesc), len(file_specialties_specialties_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specialties_specialties_proto_goTypes,
		DependencyIndexes: file_specialties_specialties_proto_depIdxs,
		MessageInfos:      file_specialties_specialties_proto_msgTypes,
	}.Build()
	File_specialties_specialties_proto = out.File
	file_specialties_specialties_proto_goTypes = nil
	file_specialties_specialties_proto_depIdxs = nil
}
