// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/appointments.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Appointment message
type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_appointments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_appointments_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Request & Response
type GetAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentsRequest) Reset() {
	*x = GetAppointmentsRequest{}
	mi := &file_proto_appointments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentsRequest) ProtoMessage() {}

func (x *GetAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointments_proto_rawDescGZIP(), []int{1}
}

type GetAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentsResponse) Reset() {
	*x = GetAppointmentsResponse{}
	mi := &file_proto_appointments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentsResponse) ProtoMessage() {}

func (x *GetAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointments_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

var File_proto_appointments_proto protoreflect.FileDescriptor

const file_proto_appointments_proto_rawDesc = "" +
	"\n" +
	"\x18proto/appointments.proto\x12\fappointments\"G\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"\x18\n" +
	"\x16GetAppointmentsRequest\"X\n" +
	"\x17GetAppointmentsResponse\x12=\n" +
	"\fappointments\x18\x01 \x03(\v2\x19.appointments.AppointmentR\fappointments2t\n" +
	"\x12AppointmentService\x12^\n" +
	"\x0fGetAppointments\x12$.appointments.GetAppointmentsRequest\x1a%.appointments.GetAppointmentsResponseB0Z.github.com/salahfarzin/appointment/proto;protob\x06proto3"

var (
	file_proto_appointments_proto_rawDescOnce sync.Once
	file_proto_appointments_proto_rawDescData []byte
)

func file_proto_appointments_proto_rawDescGZIP() []byte {
	file_proto_appointments_proto_rawDescOnce.Do(func() {
		file_proto_appointments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointments_proto_rawDesc), len(file_proto_appointments_proto_rawDesc)))
	})
	return file_proto_appointments_proto_rawDescData
}

var file_proto_appointments_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_appointments_proto_goTypes = []any{
	(*Appointment)(nil),             // 0: appointments.Appointment
	(*GetAppointmentsRequest)(nil),  // 1: appointments.GetAppointmentsRequest
	(*GetAppointmentsResponse)(nil), // 2: appointments.GetAppointmentsResponse
}
var file_proto_appointments_proto_depIdxs = []int32{
	0, // 0: appointments.GetAppointmentsResponse.appointments:type_name -> appointments.Appointment
	1, // 1: appointments.AppointmentService.GetAppointments:input_type -> appointments.GetAppointmentsRequest
	2, // 2: appointments.AppointmentService.GetAppointments:output_type -> appointments.GetAppointmentsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_appointments_proto_init() }
func file_proto_appointments_proto_init() {
	if File_proto_appointments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointments_proto_rawDesc), len(file_proto_appointments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointments_proto_goTypes,
		DependencyIndexes: file_proto_appointments_proto_depIdxs,
		MessageInfos:      file_proto_appointments_proto_msgTypes,
	}.Build()
	File_proto_appointments_proto = out.File
	file_proto_appointments_proto_goTypes = nil
	file_proto_appointments_proto_depIdxs = nil
}
